name: CJPanel-Plugin
main: me.RyanWild.CJFPanelPlugin.CJFPanelPlugin
version: 0.3.2
description: The Plugin that works with the CJPanel
depend: [TotalFreedomMod]

commands:
  server:
    description: Access the API command.