name: CJPanel-Plugin
main: me.RyanWild.CJFPanelPlugin.CJFPanelPlugin
version: 0.3
description: The Plugin that works with the CJPanel

commands:
  server:
    description: Access the API command.